spring.application.name=learn-spring-boot
#spring.profiles.active=dev

currency-service.url=http:/test.com
currency-service.username=testname
currency-service.key=testkey

management.endpoints.web.exposure.include=*